### ISSUE TITLE
Manager Page- Additional name fields defaulting to NULL should default to Primary Name

### ISSUE THREAD

**Issue by baffmt** [UVIMCO/PRISM_Admin#10]
The following fields on the manager page default to NULL but should default to the same value as dws_risk.Manager.Name
dws_risk.Manager.InternalReporting
dws_risk.Manager.BoardReporting

* Note this should only occur on the first Insert, not on updates.
** Also note that similarly the Fund page behavior for dws_risk.Fund.InternalReporting dws_risk.Fund.BoardReporting should use dws_risk.Fund.Name.

**Comment by uvimcomatt** [comment]
Done

**Comment by uvimcomatt** [comment]
Completed, checked in, and published.
