### ISSUE TITLE
Fund Page- Fields filling '' (blank) instead of NULL

### ISSUE THREAD

**Issue by baffmt** [UVIMCO/PRISM_Admin#3]
The following fields submit a blank string instead of a NULL value to the database when not entered in the interface:
dws_risk.Fund.Legacy_FundName
dws_risk.Fund.Descrip

**Comment by uvimcomatt** [comment]
Fixed

**Comment by uvimcomatt** [comment]
All fund problems are fixed.  Checked in changes, but not yet deployed to IIS.  Waiting to get manager portion fixed too.

**Comment by uvimcomatt** [comment]
Completed, checked in, and published.
