### ISSUE TITLE
Fund Page- bit value defaults to 1 but should default to 0

### ISSUE THREAD

**Issue by baffmt** [UVIMCO/PRISM_Admin#7]
The following values on the Fund page default to 1 when not supplied, however they should default to 0 instead:
dws_risk.Fund.InclInForecast
dws_risk.Fund.TriggersUBTI

**Comment by uvimcomatt** [comment]
Pretty sure this is working correctly.  In all of my testing, default bit value for these fields is 0 unless the the checkbox is checked (in which case a 1 is inserted).

**Comment by uvimcomatt** [comment]
All fund problems are fixed.  Checked in changes, but not yet deployed to IIS.  Waiting to get manager portion fixed too.

**Comment by uvimcomatt** [comment]
Completed, checked in, and published.
