### ISSUE TITLE
Fund Page- bit value defaults to 0 but should default to NULL

### ISSUE THREAD

**Issue by baffmt** [UVIMCO/PRISM_Admin#8]
The following values on the Fund page default to 0 when not supplied, however they should default to NULL instead:
dws_risk.Fund.VintageYear

**Comment by uvimcomatt** [comment]
Fixed

**Comment by uvimcomatt** [comment]
All fund problems are fixed.  Checked in changes, but not yet deployed to IIS.  Waiting to get manager portion fixed too.

**Comment by uvimcomatt** [comment]
Completed, checked in, and published.
